# Generated by Django 2.0 on 2020-04-07 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=70)),
                ('jumlah', models.IntegerField()),
                ('harga', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pemilik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Toko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=50)),
                ('pemilik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokopedia.Pemilik')),
            ],
        ),
        migrations.AddField(
            model_name='barang',
            name='toko',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokopedia.Toko'),
        ),
    ]
