# Generated by Django 2.0 on 2020-04-07 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='kategory',
            field=models.CharField(choices=[('elektronik', 'Elektronik'), ('fashion', 'Fashion'), ('olahraga', 'Olahraga')], default='elektronik', max_length=50),
        ),
        migrations.AddField(
            model_name='barang',
            name='status',
            field=models.CharField(choices=[('baru', 'Baru'), ('bekas', 'Bekas')], default='baru', max_length=50),
        ),
        migrations.AlterField(
            model_name='barang',
            name='toko',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barang', to='tokopedia.Toko'),
        ),
        migrations.AlterField(
            model_name='toko',
            name='pemilik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toko', to='tokopedia.Pemilik'),
        ),
    ]
