# Generated by Django 2.0 on 2020-04-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0002_auto_20200407_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemilik',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
        ),
    ]
