# Generated by Django 2.0 on 2020-04-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0004_auto_20200407_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemilik',
            name='toko',
        ),
        migrations.AddField(
            model_name='pemilik',
            name='no_hp',
            field=models.CharField(default='', max_length=20),
        ),
    ]
