# Generated by Django 2.0 on 2020-04-12 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0006_barang_poto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='toko',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tokopedia.Toko'),
        ),
    ]
