# Generated by Django 2.0 on 2020-04-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0007_auto_20200412_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='poto',
            field=models.ImageField(default='', upload_to='img/'),
        ),
    ]
