# Generated by Django 2.0 on 2020-05-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokopedia', '0009_auto_20200412_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='poto',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
